name: check-meta
on: push
jobs:
  logos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-yq
        run: wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 && chmod +x /usr/local/bin/yq
