name: check-meta
on: push
jobs:
  check-logos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-yq
        run: sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq
      - name: check-logos
        run: |
          for d in */; do
            [[ -z $(yq read .meta/logos.yaml "(id==${d%/})") ]] && missing+=("${d%/}")
          done
          [[ -n "${missing[@]}" ]] && { echo "Logo IDs missing from meta file (.meta/logos.yaml): ${missing[@]}"; exit 1; }
