name: validate-meta-files
on: push
env:
  META_LOGOS: .meta/logos.yaml
  SCHEMA_LOGOS: .meta/schema-logos.json
jobs:
  logos-structural:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-ajv
        run: sudo npm install -g ajv-cli
      - name: validate
        run: ajv validate --verbose  --all-errors -s "$SCHEMA_LOGOS" -d "$META_LOGOS"
  logos-semantic:
    needs: logos-structural
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Try getting yq binary from cache (https://github.com/actions/cache#skipping-steps-based-on-cache-hit) and only install if cache miss
      - name: install-yq
        run: sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq
      - name: validate
        run: |
          for d in */; do
            [[ -z $(yq read "$META_LOGOS" "(id==${d%/})") ]] && missing+=("${d%/}")
          done
          [[ -n "${missing[@]}" ]] && { echo "The following logos have no entry in $META_LOGOS: ${missing[@]}"; exit 1; } || exit 0
