on: push
env:
  SCHEMA: .schemas/commit.schema.json
jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # TODO: Put ajv binary (/usr/local/bin/ajv) in cache and access from there
      - name: install-ajv
        run: sudo npm install -g ajv-cli
      - name: install-yq
        run: sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq
      - name: validate
        run: |
          set -e
          # Get the most recent commit where this workflow succeeded
          base=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$(basename ${{ github.workflow }})/runs?status=success" | jq -r '.workflow_runs | sort_by(.run_number) | last | .head_sha')
          # If the workflow has never been run before, use the root commit as the base
          [[ "$base" = null ]] && base=$(git rev-list --max-parents=0 HEAD)
          echo "$base"
          # Get all SVG files that have been added or modified since the base commit
          files=($(git diff-tree --name-only --diff-filter=AM -r "$base" HEAD | sed -ne '/^[^\.].*\/.*\.svg$/p'))
          # Determine the commit that last added/modified each file
          declare -A map
          for f in "${files[@]}"; do
            map[$(git log -n 1 --format=%H "$f")]+="$f "
          done
          # Validate the YAML spec in the commit message of each identified commit
          for c in "${!map[@]}"; do
            yaml=$(mktemp -d)/tmp.yaml
            git log --format=%b -n 1 "$c" | sed -n '/^---$/ { :a; p; n; ba; }' >"$yaml"
            # Ensure that YAML spec is not empty
            if ! [[ -s "$yaml" ]]; then
              echo -e "$c: missing YAML spec"
              echo "The following files have been last added/modified by this commit:"
              echo ${map[$c]% } | tr ' ' $'\n'
              exit 1
            fi
            # Ensure that YAML spec matches schema
            if ! out=$(ajv validate -s "$SCHEMA" -d "$yaml" 2>&1); then
              echo -e "$c: YAML spec is invalid"
              cat "$yaml"
              echo "$out"
              exit 1
            fi
            # Ensure that YAML spec covers all files last added/modified by this commit
            keys=$(yq read -p p "$yaml" '*' | tr -d '"')
            if ! [[ "$keys" =~ ^source$|^edited$|^converted ]]; then
              for f in ${map[$c]}; do
                grep -q "^$f$" <<<"$keys" || missing+=("$f")
              done
              if [[ "${missing[@]}" ]]; then
                echo "$c: YAML spec does not cover all added/modified files"
                cat "$yaml"
                echo "The following files are not covered by the YAML spec:"
                printf '%s\n' "${missing[@]}"
                exit 1
              fi
            fi
          done
