name: validate-commit-messages
on: push
env:
  SCHEMA: .schemas/commit-msg.schema.json
jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: git log -n 5
