name: validate-meta-file
on: push
env:
  META: .meta.yaml
  SCHEMA: .meta-schema.json
jobs:
  structural:
    name: Structural validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: Put ajv binary (/usr/local/bin/ajv) in cache and access from there
      - name: install-ajv
        run: sudo npm install -g ajv-cli
      - name: validate
        run: ajv validate --verbose  --all-errors -s "$SCHEMA_LOGOS" -d "$META_LOGOS"
  semantic-ids:
    needs: structural
    name: Semantic validation: check each directory has corresponding meta item
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: put yq binary (/usr/local/bin/yq) in cache and access from there (https://github.com/actions/cache#skipping-steps-based-on-cache-hit)
      - name: install-yq
        run: sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq
      - name: validate
        run: |
          for d in */; do
            [[ -z $(yq read "$META_LOGOS" "(id==${d%/})") ]] && missing+=("${d%/}")
          done
          [[ -n "${missing[@]}" ]] && { echo "The following logos have no entry in $META_LOGOS: ${missing[@]}"; exit 1; } || exit 0
  semantic-ids:
    needs: structural
    name: Semantic validation: check meta item has corresponding directory
    runs-on: ubuntu-latest
    steps: 
  semantic-associations:
    needs: structural
    name: Semantic validation: associations
    runs-on: ubuntu-latest
    steps:
