name: validate-commit-messages
on: push
env:
  SCHEMA: .schemas/commit-msg.schema.json
jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get-commits
        run: |
          echo "COMMITS<<EOF" >>"$GITHUB_ENV"
          git log --reverse --format=%H commit-msg-validation-head..HEAD) >>"$GITHUB_ENV"
          echo EOF >>"$GITHUB_ENV"
      - name: get-files
        run: echo "$COMMITS"
